# Generated by Django 3.0.3 on 2021-03-13 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(help_text='Enter Months', null=True)),
                ('locationCount', models.IntegerField(blank=True, null=True)),
                ('keywordCount', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.FileField(blank=True, null=True, upload_to='software')),
                ('whatsapp', models.FileField(blank=True, null=True, upload_to='software')),
                ('instagram', models.FileField(blank=True, null=True, upload_to='software')),
            ],
        ),
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_count', models.IntegerField(default=10)),
                ('isActive', models.BooleanField(default=True)),
                ('reseller', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNo', models.IntegerField(null=True)),
                ('ip_address', models.CharField(blank=True, help_text='do not fill this field', max_length=256, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Whatsapp',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Base')),
                ('DemoDate', models.DateField(blank=True, null=True)),
                ('licenceExpireDate', models.DateField(blank=True, null=True)),
                ('isPaid', models.BooleanField(blank=True, default=False, help_text='only click when amount is paid')),
                ('isActive', models.BooleanField(blank=True, default=False)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Plan')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('reseller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Reseller')),
            ],
            bases=('users.base',),
        ),
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Base')),
                ('DemoDate', models.DateField(blank=True, null=True)),
                ('licenceExpireDate', models.DateField(blank=True, null=True)),
                ('isPaid', models.BooleanField(blank=True, default=False, help_text='only click when amount is paid')),
                ('isActive', models.BooleanField(blank=True, default=False)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Plan')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('reseller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Reseller')),
            ],
            bases=('users.base',),
        ),
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Base')),
                ('DemoDate', models.DateField(blank=True, null=True)),
                ('licenceExpireDate', models.DateField(blank=True, null=True)),
                ('isPaid', models.BooleanField(blank=True, default=False, help_text='only click when amount is paid')),
                ('isActive', models.BooleanField(blank=True, default=False)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Plan')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('reseller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Reseller')),
            ],
            bases=('users.base',),
        ),
    ]
