# Generated by Django 3.0.3 on 2021-03-23 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authtoken', '0002_auto_20160226_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNo', models.IntegerField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(blank=True, max_length=256, null=True)),
                ('price', models.IntegerField(blank=True, help_text='plan price', null=True)),
                ('duration', models.IntegerField(help_text='Enter Months', null=True)),
                ('locationCount', models.IntegerField(blank=True, null=True)),
                ('keywordCount', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.FileField(blank=True, null=True, upload_to='software')),
                ('whatsapp', models.FileField(blank=True, null=True, upload_to='software')),
                ('instagram', models.FileField(blank=True, null=True, upload_to='software')),
                ('whatsapp_class_xpath', models.TextField(blank=True, null=True)),
                ('telegram_class_xpath', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_count', models.IntegerField(default=10)),
                ('sold_token', models.IntegerField(default=0)),
                ('months', models.IntegerField(default=0)),
                ('phoneNo', models.IntegerField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('reseller', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNo', models.IntegerField(null=True)),
                ('unhash_password', models.CharField(blank=True, max_length=256, null=True)),
                ('reseller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Reseller')),
                ('token', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authtoken.Token')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Whatsapp',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Base')),
                ('duration', models.IntegerField(default=12)),
                ('DemoDate', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('licenceExpireDate', models.DateField(blank=True, null=True)),
                ('isPaid', models.BooleanField(blank=True, default=False, help_text='only click when amount is paid')),
                ('confirm_paid', models.BooleanField(default=False, help_text='do not fill this field')),
                ('isActive', models.BooleanField(blank=True, default=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('ip_address', models.CharField(blank=True, help_text='do not fill this field', max_length=256, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('reseller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Reseller')),
            ],
            bases=('users.base',),
        ),
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Base')),
                ('duration', models.IntegerField(default=12)),
                ('DemoDate', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('licenceExpireDate', models.DateField(blank=True, null=True)),
                ('isPaid', models.BooleanField(blank=True, default=False, help_text='only click when amount is paid')),
                ('confirm_paid', models.BooleanField(default=False, help_text='do not fill this field')),
                ('isActive', models.BooleanField(blank=True, default=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('ip_address', models.CharField(blank=True, help_text='do not fill this field', max_length=256, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('reseller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Reseller')),
            ],
            bases=('users.base',),
        ),
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Base')),
                ('duration', models.IntegerField(default=12)),
                ('DemoDate', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('licenceExpireDate', models.DateField(blank=True, null=True)),
                ('isPaid', models.BooleanField(blank=True, default=False, help_text='only click when amount is paid')),
                ('confirm_paid', models.BooleanField(default=False, help_text='do not fill this field')),
                ('isActive', models.BooleanField(blank=True, default=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('ip_address', models.CharField(blank=True, help_text='do not fill this field', max_length=256, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('reseller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Reseller')),
            ],
            bases=('users.base',),
        ),
    ]
