# Generated by Django 3.0.3 on 2021-03-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phoneNo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reseller',
            name='phoneNo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
