# Generated by Django 3.0.3 on 2021-03-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210313_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unhash_password',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
