# Generated by Django 3.0.3 on 2021-03-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210324_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegram',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
