# Generated by Django 3.0.3 on 2021-03-13 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_unhash_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reseller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Reseller'),
        ),
    ]
