# Generated by Django 3.0.3 on 2021-03-25 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210324_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagram',
            name='confirm_paid',
        ),
        migrations.RemoveField(
            model_name='telegram',
            name='confirm_paid',
        ),
        migrations.RemoveField(
            model_name='whatsapp',
            name='confirm_paid',
        ),
        migrations.AlterField(
            model_name='telegram',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
