# Generated by Django 3.0.3 on 2021-03-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_reseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapp',
            name='class_xpath',
            field=models.TextField(blank=True, null=True),
        ),
    ]
