# Generated by Django 3.0.3 on 2021-03-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_reseller_sold_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='telegram_class_xpath',
            field=models.TextField(blank=True, null=True),
        ),
    ]
