# Generated by Django 3.0.3 on 2021-03-19 15:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_instagram_confirm_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegram',
            name='DemoDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 19, 15, 4, 16, 554536, tzinfo=utc), null=True),
        ),
    ]
