# Generated by Django 3.0.3 on 2021-03-19 15:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210319_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagram',
            name='DemoDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 19, 15, 6, 7, 1265, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='telegram',
            name='DemoDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 19, 15, 6, 6, 997218, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='whatsapp',
            name='DemoDate',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 19, 15, 6, 7, 1265, tzinfo=utc), null=True),
        ),
    ]
