# Generated by Django 3.0.3 on 2021-03-19 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210319_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagram',
            name='DemoDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='telegram',
            name='DemoDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='whatsapp',
            name='DemoDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
