# Generated by Django 3.0.3 on 2021-03-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210319_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='instagram',
            name='ip_address',
            field=models.CharField(blank=True, help_text='do not fill this field', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='telegram',
            name='ip_address',
            field=models.CharField(blank=True, help_text='do not fill this field', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='whatsapp',
            name='ip_address',
            field=models.CharField(blank=True, help_text='do not fill this field', max_length=256, null=True),
        ),
    ]
