# Generated by Django 3.0.3 on 2021-03-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210319_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
