# Generated by Django 3.0.3 on 2021-03-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_plan_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='price',
            field=models.IntegerField(blank=True, help_text='plan price', null=True),
        ),
    ]
