# Generated by Django 3.0.3 on 2021-03-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_plan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseller',
            name='phoneNo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
