# Generated by Django 3.0.3 on 2021-03-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_reseller_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseller',
            name='months',
            field=models.IntegerField(default=0),
        ),
    ]
