# Generated by Django 3.0.3 on 2021-03-22 07:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0020_funtest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FunTest',
            new_name='Funy',
        ),
    ]
