# Generated by Django 3.0.3 on 2021-03-22 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20210322_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegram',
            name='plan',
            field=models.ForeignKey(blank=True, default=12, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Plan'),
        ),
    ]
