# Generated by Django 3.0.3 on 2021-03-22 14:52

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20210322_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegram',
            name='plan',
            field=models.ForeignKey(blank=True, default=users.models.get_plan, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Plan'),
        ),
    ]
