# Generated by Django 3.0.3 on 2021-03-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20210323_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phoneNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
