# Generated by Django 3.0.3 on 2021-03-23 04:35

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20210323_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagram',
            name='plan',
            field=models.ForeignKey(blank=True, default=users.models.get_plan, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Plan'),
        ),
        migrations.AlterField(
            model_name='whatsapp',
            name='plan',
            field=models.ForeignKey(blank=True, default=users.models.get_plan, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Plan'),
        ),
    ]
