# Generated by Django 3.0.3 on 2021-03-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20210323_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagram',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='telegram',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='whatsapp',
            name='plan',
        ),
        migrations.AddField(
            model_name='instagram',
            name='duration',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='telegram',
            name='duration',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='whatsapp',
            name='duration',
            field=models.IntegerField(default=12),
        ),
    ]
